#!/usr/bin/env zsh

# Quick shortcuts
export HOME=/Users/couto;
export DOTFILES=${HOME}/.dotfiles

# Fix locales
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Editors
export ATOM_PATH="/opt/homebrew-cask/Caskroom/atom/latest"
export ATOM="$ATOM_PATH/Atom.app"
export EDITOR=$(which vim)
export VISUAL="$(which vim)"

# Configurations
export NVM_DIR=$HOME/.nvm

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Increase history
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

# Manpages
export MANPATH=$(brew --prefix)/opt/coreutils/libexec/gnuman:$MANPATH;

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Path
path=(
  "${HOME}/.bin"
  $(brew --prefix)/opt/coreutils/libexec/gnubin
  $(brew --prefix)/opt
  /usr/local/bin
  /usr/local/sbin
  $path
);
typeset -U path

# rbenv, pyenv, nvm and the likes
source "$(brew --prefix nvm)/nvm.sh"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
