#!/usr/bin/env zsh

# Quick shortcuts
export HOME="/Users/$USER";
export DOTFILES=${HOME}/.dotfiles
export BREW="${HOME}/.homebrew/bin/brew"

# Fix locales
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Editors
export EDITOR="$(which vim)";
export VISUAL="$(which vim)";

# Configurations
export NVM_DIR=$HOME/.nvm
#
# Homebrew options (no analytics, local install)
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_CASK_OPTS='--appdir=~/Applications --caskroom=~/.homebrew/Caskroom'

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Increase history
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Path
path=(
  "${HOME}/.bin"
  "${HOME}/.homebrew/bin"
  $(brew --prefix)/opt/curl/bin
  $(brew --prefix)/opt/coreutils/libexec/gnubin
  $(brew --prefix)/opt
  /usr/local/bin
  /usr/local/sbin
  $path
);
typeset -U path

# rbenv, pyenv, nvm and the likes
. $(brew --prefix nvm)/nvm.sh
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Manpages
export MANPATH=$(brew --prefix)/opt/coreutils/libexec/gnuman:$MANPATH;

# FZF Settings
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

