#!/usr/bin/env zsh

# Quick shortcuts
export HOME="/Users/$USER";
export DOTFILES=${HOME}/.dotfiles
export HOMEBREW_DIR="${HOME}/.homebrew"
export BREW="${HOMEBREW_DIR}/bin/brew"

# Fix locales
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Editors
export EDITOR="$(which nvim)";
export VISUAL="$(which nvim)";

# Homebrew options (no analytics, local install)
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_CASK_OPTS='--appdir=~/Applications'

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Increase history
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Path
typeset -U path
path=(
  "${HOME}/.bin"
  "${HOMEBREW_DIR}/opt/curl/bin"
  "${HOMEBREW_DIR}/opt/coreutils/libexec/gnubin"
  "${HOMEBREW_DIR}/bin"
  "${HOMEBREW_DIR}/opt"
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  $path
);

# export GPG_TTY="$(tty)"
# export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
# gpgconf --launch gpg-agent

gpgconf --launch gpg-agent
export SSH_AUTH_SOCKET=$HOME/.gnupg/S.gpg-agent.ssh


export ASDF_DIR="${HOMEBREW_DIR}/opt/asdf"

# Manpages
export MANPATH="${HOMEBREW_DIR}/opt/coreutils/libexec/gnuman:$MANPATH;"

# FZF Settings
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

