#!/usr/bin/env zsh

# load zgen
source "${HOME}/.zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
  echo "Creating a zgen save"

  # bulk load
  zgen loadall <<EOPLUGINS
    mafredri/zsh-async
    sindresorhus/pure
    rupa/z
    "${HOME}/.zsh/osx"
    "${HOME}/.zsh/fs"
    "${HOME}/.zsh/network"
    "${HOME}/.zsh/git"
    "${HOME}/.zsh/history"
    zsh-users/zsh-completions src
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-history-substring-search
    "${HOMEBREW_DIR}/share/zsh-completions"
    "${HOMEBREW_DIR}/opt/git-extras/share/git-extras/git-extras-completion.zsh"
    "${ASDF_DIR}/asdf.sh"
EOPLUGINS
  # save all to init script
  zgen save
fi

autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# bind UP and DOWN arrow keys
zmodload zsh/terminfo

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind UP and DOWN arrow keys (compatibility fallback
# for Ubuntu 12.04, Fedora 21, and MacOSX 10.9 users)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

## VI mode ########################################
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Enable incremental substring search
bindkey '^R' history-incremental-search-backward

# FZF settings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# This slows down the zsh startup time by approx 60ms
# if [ $commands[kubectl] ]; then
#   source <(kubectl completion zsh)
# fi

. "${ASDF_DIR}/etc/bash_completion.d/asdf.bash"
