#!/usr/bin/env zsh

# load zgen
source "${HOME}/.zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
  echo "Creating a zgen save"

    # mafredri/zsh-async
    # sindresorhus/pure
  
  # bulk load
  zgen loadall <<EOPLUGINS
    rupa/z
    "${HOME}/.zsh/osx"
    "${HOME}/.zsh/fs"
    "${HOME}/.zsh/network"
    "${HOME}/.zsh/git"
    "${HOME}/.zsh/history"
    zsh-users/zsh-completions src
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-history-substring-search
    "${HOMEBREW_DIR}/share/zsh-completions"
    "${HOMEBREW_DIR}/opt/git-extras/share/git-extras/git-extras-completion.zsh"
    "${ASDF_DIR}/asdf.sh"
EOPLUGINS
  zgen load denysdovhan/spaceship-prompt spaceship
  # save all to init script
  zgen save
fi

autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# bind UP and DOWN arrow keys
zmodload zsh/terminfo

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind UP and DOWN arrow keys (compatibility fallback
# for Ubuntu 12.04, Fedora 21, and MacOSX 10.9 users)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

## VI mode ########################################
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Enable incremental substring search
bindkey '^R' history-incremental-search-backward

# Path
typeset -U path
path=(
  "${HOME}/.bin"
  "${HOMEBREW_DIR}/opt/curl/bin"
  "${HOMEBREW_DIR}/opt/coreutils/libexec/gnubin"
  "${HOMEBREW_DIR}/bin"
  "${HOMEBREW_DIR}/opt"
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  $path
);

export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent


# FZF settings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# This slows down the zsh startup time by approx 60ms
# if [ $commands[kubectl] ]; then
#   source <(kubectl completion zsh)
# fi


# Spaceship customizations
export SPACESHIP_TIME_SHOW=true
export SPACESHIP_PACKAGE_SHOW=false

. "${ASDF_DIR}/etc/bash_completion.d/asdf.bash"
