install zsh
install tmux reattach-to-user-namespace
install htop-osx

install nvm
install rbenv ruby-build
install pyenv

install dnsmasq
install nmap
install ettercap
install hydra
install httpie
install stunnel

install git
install git-extras
install git-flow
install gist

install shellcheck
install ansible

tap theory/sqitch
install sqitch_pg

install apg
install sshfs

install chromaprint
install archey
