#!/usr/bin/env zsh

HOMEBREW_FOLDER="${HOME}/.homebrew"
BIN="${HOMEBREW_FOLDER}/bin/brew"


TAPS=(
  thoughtbot/formulae
  caskroom/versions
  caskroom/fonts
);

PACKAGES=(
  coreutils
  dnsmasq --with-dnssec
  dnscrypt-proxy
  tree
  nvm
  shellcheck
  rbenv
  rcm
  pyenv
  tmux
  z
  zsh
);

APPS=(
  atom
  iterm2
  slack
  macpass
  vagrant
  virtualbox
  the-unarchiver
  firefox
  google-chrome
  google-chrome-canary
);

FONTS=(
  font-fira-mono
  font-dejavu-sans-mono-for-powerline
);


setup_homebrew() {
  mkdir -p ${HOMEBREW_FOLDER} && curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C ${HOMEBREW_FOLDER}
}

setup_cask() {
  echo "${BIN}"
  ${BIN} tap caskroom/cask

}

setup_common_taps() {
  local taps=(
    'caskroom/versions'
    'caskroom/fonts'
  );

  for i in ${tap}; do
    ${BIN} tap ${i}
  done
}

main() {

  if [[ -n ${BIN} ]]; then
    echo "Installing homebrew";
    setup_homebrew;

    echo "Installing brew-cask";
    setup_cask
    setup_common_taps
  fi
}

main
