#!/usr/bin/env bash


main() {
 

  echo "Post-Up Hook for dnscrypt";

  export PLIST='/Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist';
  export MARKER='<string>/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>';
  export ARGS='<string>--local-address=127.0.0.1:5355</string><string>--resolvers-list=/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv</string>';

  sudo cp -fv /usr/local/opt/dnscrypt-proxy/*.plist /Library/LaunchDaemons
  sudo chown root "${PLIST}"; 

  sudo sed -i '' 's|'${MARKER}'|'${MARKER}'\'$'\n'${ARGS}'|' ${PLIST};

  sudo launchctl load ${PLIST}
}
